### ISSUE TITLE
[BUG]🐛 send photo by URL throws an error.

### ISSUE THREAD

**Issue by 7flash** [ferrisgram/ferrisgram#6]
### Steps to Reproduce

the same as README example, but send_photo

### Expected behaviour

sendPhoto API method should support both InputFile and String, as per documentation

![Uploading image.png…]()

### Actual behaviour

but it throws an error because auto generated type expects InputFile only

### Operating System

Windows

### Version of Rust, Ferrisgram & dependencies

```shell
latest
```

### Additional Context

![image](https://user-images.githubusercontent.com/4569866/184630324-11dab029-c9bb-4c4a-8a11-1cd7f1e85066.png)

**Comment by celestix** [comment]
Hello, since the library is yet under construction. Working of the methods related to `InputFile` are yet to be determined. We will let this issue opened until we fix it. 
Thanks

**Comment by celestix** [comment]
Hey @7flash! would you like to join us and become a maintainer of the project?

**Comment by 7flash** [comment]
> Hey @7flash! would you like to join us and become a maintainer of the project?

Thanks for invitation! Send me a message in telegram @berliangur

**Comment by celestix** [comment]
> > Hey @7flash! would you like to join us and become a maintainer of the project?
> 
> Thanks for invitation! Send me a message in telegram @berliangur

Hello! I've sent you a message on telegram through t.me/CaptainPicard

**Comment by celestix** [comment]
This has been fixed.
